### ISSUE TITLE
Set style selected country on summary per country with card-header style

### ISSUE THREAD

**Issue by pararang** [pararang/vue-covid#12]
existing:
![Screenshot from 2020-03-24 21-30-44](https://user-images.githubusercontent.com/8720184/77437037-c748e300-6e16-11ea-8098-beb78166ed3c.png)

expected:

![Screenshot from 2020-03-24 21-30-53](https://user-images.githubusercontent.com/8720184/77437056-cd3ec400-6e16-11ea-944f-d4079c939559.png)

**Comment by pararang** [comment]
Hi @maulana20, need help for this one :)

**Comment by maulana20** [comment]
Ok .. I will try
