### ISSUE TITLE
Sometimes cant render the apexchart completely

### ISSUE THREAD

**Issue by pararang** [pararang/vue-covid#4]
Sometimes the y-axis not rendered, sometimes the tooltip for the x-axis not rendered too that cause the `NaN`.

![Screenshot from 2020-03-14 02-48-39](https://user-images.githubusercontent.com/8720184/76654874-98bd4380-659e-11ea-9267-b9b1cb298065.png)

**Comment by izzatzr** [comment]
is there any error you can paste here explaining about the apexchart error ? and maybe if you could try to write step by step on how to reproduce this issue . thank you

**Comment by pararang** [comment]
Hai @izzatzr , thanks for the feedback. This issue already solved by changing the library with Google Chart.
