### ISSUE TITLE
Fix the summary card if number is more than 6 characters

### ISSUE THREAD

**Issue by pararang** [pararang/vue-covid#42]
**Describe the bug**
On the summary card, the number will create a new line if it has more than 6 chars, 

**To Reproduce**
1. Go to home page

**Expected behavior**
The cards still have the same size.

**Screenshots**
![Screenshot from 2020-10-02 00-12-05](https://user-images.githubusercontent.com/8720184/94842043-16ff0b80-0445-11eb-8908-b70ff29c1b1b.png)

**Comment by codybarr** [comment]
On it. @pararang can you assign to me?

**Comment by pararang** [comment]
assigned to you @codybarr, please do it.

**Comment by pararang** [comment]
merged, thanks @codybarr
