### ISSUE TITLE
Fix the chart on the tab Tren Perhari

### ISSUE THREAD

**Issue by pararang** [pararang/vue-covid#43]
**Describe the bug**
The chart stopped in the middle of the x-axis

**To Reproduce**
1. Go to the home page, 
2.click the tab Tren Perhari

**Expected behavior**
The chart should be fully shown to the end of the x-axis

**Screenshots**
![Screenshot from 2020-10-02 00-37-03](https://user-images.githubusercontent.com/8720184/94844186-0ef49b00-0448-11eb-823a-991b0ca22e51.png)

**Desktop**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by MaximeKoitsalu** [comment]
Hey @pararang, just forked your repo and tried running it but it seems there are some 502 errors trying to fetch the data for the graph.  https://indonesia-covid-19.mathdro.id/api/harian

![image](https://user-images.githubusercontent.com/8655862/94851081-39cef700-0428-11eb-8afa-99ea95f5d048.png)

**Comment by pararang** [comment]
tried it on my local, there's no problem on that endpoint, intermittent issue maybe. can you confirm that again @MaximeKoitsalu ?

**Comment by MaximeKoitsalu** [comment]
Hmm, I still get the same error today. Visiting the endpoint I get the following message. I'll start on the other task, try this one again and if I can't make it work I'll let someone else try 😅 
![image](https://user-images.githubusercontent.com/8655862/94934474-12316a80-04cc-11eb-8c10-1b2c385b57ac.png)

**Comment by MaximeKoitsalu** [comment]
Still couldn't make it work. I hope someone else will help you with this issue. Good luck!

**Comment by paymin** [comment]
Hi @pararang, i just tried to fork your project and trying to solve your issue. It is just what you need?

![image](https://user-images.githubusercontent.com/21330168/95301982-847ac400-08ab-11eb-940e-12982ca90e75.png)

**Comment by paymin** [comment]
here is some improvement, i think there are double value in your data
![image](https://user-images.githubusercontent.com/21330168/95303447-64e49b00-08ad-11eb-9cab-a927ceec5c9d.png)

**Comment by pararang** [comment]
ok, assigned to you @paymin. Please create PR.
