### ISSUE TITLE
Interval xAxis on Chart Indonesia:Tren Per Hari Changes After Click Muat Ulang 

### ISSUE THREAD

**Issue by pararang** [pararang/vue-covid#48]
**Describe the bug**
Value and range value of xAxis on Tren Perhari changes every we click Muat Ulang.

**To Reproduce**
1. Go to Home
2. Click on Muat Ulang in Indonesia Section -> Tab Tren Perhari

**Expected behavior**
Range of value xAxis not  changes after click button Muat Ulang

**Screenshots**
Before click
![Screenshot from 2020-10-18 01-43-18](https://user-images.githubusercontent.com/8720184/96351192-048efe00-10e4-11eb-808d-f65c30be2ffd.png)

 After Click
![Screenshot from 2020-10-18 01-43-49](https://user-images.githubusercontent.com/8720184/96351193-0b1d7580-10e4-11eb-9ece-1647f12607a2.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version: Latest

**Smartphone (please complete the following information):**
  n/a

**Additional context**
Broke after PR #47

**Comment by pararang** [comment]
Hi @paymin , could help to check this issue? Please confirm if you can solve this, so I can assign it to you. Thanks

**Comment by paymin** [comment]
ok. i'll take a look
